version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/common/*"
      - "/provider/*/data-guard"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "npm"
  - package-ecosystem: "docker"
    directories:
      - "/common/*"
      - "/provider/*/data-guard"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    labels:
      - "dependencies"
      - "docker"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    labels:
      - "dependencies"
      - "github-actions"
