FROM node:20-alpine
WORKDIR /app
COPY _lib /app/provider/_lib
COPY dynatrace/data-guard /app/provider/dynatrace/data-guard
WORKDIR /app/provider/dynatrace/data-guard
EXPOSE 6317
ENV PORT=6317
HEALTHCHECK --interval=30s --timeout=3s CMD wget -qO- http://localhost:6317/health || exit 1
CMD ["node", "index.js"]
