apiVersion: v1
kind: Service
metadata:
  name: schema-validator
  namespace: poc-mcp-trust-plane
  labels:
    app: schema-validator
    autopoc.io/project: mcp-trust-plane
spec:
  type: ClusterIP
  selector:
    app: schema-validator
  ports:
    - port: 6005
      targetPort: 6005
