FROM registry.access.redhat.com/ubi9/nodejs-22

WORKDIR /opt/app-root/src

COPY package.json index.js ./

ENV PORT=6007

RUN chgrp -R 0 /opt/app-root && chmod -R g=u /opt/app-root

EXPOSE 6007

USER 1001

CMD ["node", "index.js"]
