FROM registry.access.redhat.com/ubi9/nodejs-22

WORKDIR /opt/app-root/src

COPY package.json index.js ./

ENV PORT=6005

USER 0
RUN chgrp -R 0 /opt/app-root && chmod -R g=u /opt/app-root
USER 1001

EXPOSE 6005

CMD ["node", "index.js"]
