name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions: read-all
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          find . -name "package.json" -not -path "*/node_modules/*" -execdir npm install \;
      - name: Build common images
        run: |
          for f in $(find ./common -name "Dockerfile"); do
            dir=$(dirname "$f")
            echo "Building $f with context $dir"
            docker build -f "$f" -t "$(basename "$dir")" "$dir"
          done
      - name: Build provider images
        run: |
          for f in $(find ./provider -name "Dockerfile"); do
            echo "Building $f with context ./provider"
            docker build -f "$f" -t "$(basename "$(dirname "$f")")" ./provider
          done
